cal-itp/calitp-py

README.md
calitp/tables.py
calitp/tests/test_tables.py
requirements.txt

* Adds a basic test for the autotable functionality
* adds siuba to requirements.txt, so tests will pass
* modifies Autotable, so that rather than `<schema_name>_<table>` you use `<schema_name>.<table>`. This let's see the schemas first, then the specific tables when autocompleting.

Feat siuba autotable

---

README.md
calitp/config.py
calitp/sql.py
calitp/storage.py
calitp/tests/conftest.py
calitp/tests/test_sql.py
calitp/tests/test_storage.py
calitp/tests/test_tables.py
requirements.txt

This PR switches the calitp library to use `cal-itp-data-infra-staging` for bigquery tables when AIRFLOW_ENV is "development". It adds a simple test of storage.
(paired w/ Charlie to test it on airflow)

Feat sql staging

---

README.md
calitp/__init__.py
calitp/config.py
calitp/storage.py

This PR fixes an issue preventing the pipeline from doing the combination of these things:
* not cloud: run locally
* as pipeline: allow writing data to warehouses
It separates out the 3 dimensions of use: cloud, pipeline, development. It documents what each dimension allows: pipeline to write, development for storage / db locations, cloud for authentication type.

fix(storage): add CALITP_AUTH to detect when on the cloud

---

README.md
calitp/sql.py
docker-compose.yml

Adds the option to specify a path to a service key, so we can prototype jupyter hub end-to-end.

feat: optional env var for service key

---

_jupyterhub/requirements.txt

Adding these libraries to _jupyterhub/requirements.txt:
- plotly==5.5.0
- folium==0.12.1.post1
- branca==0.4.2
- altair_saver==0.5.0
- vega==3.5.0
- pygeos==0.12.0
- rtree==0.9.7
- openpyxl==3.0.9
- python-dotenv==0.19.2
Libraries that were already included in image:
- calitp
- geopandas
- numpy
- pandas
- altair
- matplotlib
- plotnine
- seaborn
- ipyleaflet
- ipywidgets
- fiona
- shapely
For reference: [Tiffany's list](https://github.com/cal-itp/data-analyses/blob/main/_shared_utils/setup.py#L19)

Updated JupyterHub requirements.txt with Tiffany's list

---

README.md

This PR will address:
Issue [#938](https://github.com/cal-itp/data-infra/issues/938) in the data-infra repo
This issue will add to the docs the video that Michael created before leaving regarding updating and releasing new jupyterhub images.
Video URL:
https://www.loom.com/share/1d3b00afe6314fccac55c0ce9b22ec02
Location to add:
~~/kubernetes/JupyterHub/updating~~
repo: calitp-py/readme

Adding Loom tutorial to deploy JupyterHub Images

---

calitp/__init__.py
calitp/__main__.py
calitp/protobuff.py
requirements.txt
setup.py

This is in response to https://github.com/cal-itp/data-infra/issues/1142
If you haven't already, clone this repo and install it locally (this can be inside a venv)
``` shell
git clone git@github.com:cal-itp/calitp-py.git
pip install -e ./calitp-py
```
Next check the `python -m calitp --help` and make sure the instructions are good. Here are some sample usages:
``` shell
python -m calitp random-protobuff 295/0/gtfs_rt_service_alerts_url
python -m calitp random-protobuff 295/0/*
python -m calitp random-protobuff 295/0/ --date 2022-02-23
python -m calitp random-protobuff 295/0/ --date 2022-02-23T16:01:24
python -m calitp random-protobuff 295/0/ --date 2022-02-23T16
python -m calitp random-protobuff 295/0/ --date 2022-02-23T16:01
python -m calitp random-protobuff 295/0/ --format json
```

adding random protobuff function and a cli to access it

---

_jupyterhub/requirements.txt

This PR effects:
_jupyterhub/requirements.txt
* Bumps up the calitp version in the jupyter image to 0.0.12

jupyter image(requirements): bumping up calitp version

---

.github/workflows/ci.yml
.pre-commit-config.yaml

This PR addresses dependency issues in calitp-py
`.github/workflows/ci.yml`
* pinned the version of `google-github-actions` to `v0` per their recommendation due to the change from master to main
* This need was flagged in [this GH issue](https://github.com/google-github-actions/setup-gcloud/issues/539)
`.pre-commit-config.yml`
* bumped up version of `black` known to cause dependency issues to `22.3.0`
* Flagged in this [Slack thread](https://cal-itp.slack.com/archives/C02KH3DGZL7/p1648586172862549)

calitp(pre-commit): google-github-actions pinned to v0, bumped up black formatting

---

calitp/__init__.py
calitp/__main__.py
calitp/config.py
calitp/tests/test_tables.py
requirements-dev.txt
requirements.txt
setup.py

This PR addresses dependency issues in calitp-py
Files Edited:
`setup.py`
* substituted `sqlalchemy-bigquery` for `pybigquery` which was causing dependency issues
* Flagged in this [GH issue comment](https://github.com/machow/siuba/issues/407#issuecomment-1082460991), noticed as a dependency issue in `siuba`
*addresses the first need of [issue #1313 in data-infra](https://github.com/cal-itp/data-infra/issues/1313) from @tiffanychu90, from here the Jupyter image needs to be updated
`__init__.py`
* bumped up version number for new release
Files changed by `black` formatter:
* `__main__.py`
* `config.py`
* `tests/test_tables.py`

calitp(dependencies): added sqlalchemy-bigquery to calitp-py, removed pybigquery

---

Dockerfile

First step towards completing https://github.com/cal-itp/data-analyses/issues/275
I've tested this builds locally and `gh` and `git lfs` show output.
This PR also updates gcloud to version 377 because the upstream data science book now has python 3.10, which removes some deprecated functionality that was utilized in older versions of gcloud https://issuetracker.google.com/issues/202172882

add github cli and git lfs to hub image, and update gcloud to good version

---

Dockerfile

The upstream jupyter notebook image updated to Python 3.10 and we haven't been fixing to a specific version. Consequently, deploying a new version of our Hub image (https://github.com/cal-itp/calitp-py/pull/61) caused 3.10 to be installed, which conflicts with geopandas as discovered by @amandaha8. Some GitHub issues point at libspatialindex (https://github.com/Toblerity/rtree/issues/64) so we just need to install it via apt.

make geopandas happy with python 3.10

---

calitp/storage.py
pyproject.toml

Handle `@property` partition names and combine GTFS feed extract types.
Use a storage client directly for `fetch_all_in_partition` as it's substantially faster than gcsfs.

Adjustments to support new parsing and validation Airflow jobs

---

_jupyterhub/requirements.txt

Bumping up version of voila in the Jupyter docker image to fix 404 error experienced by Natalie in the analytics team 
Tested locally

docker: bumped up voila version in jupyter image to 0.3.6 to fix 404 error

---

calitp/storage.py
pyproject.toml
tests/test_storage.py

This PR has been published as version 2022.8.23.
The primary change in this PR is splitting up the GTFS extract types. In general I'm trying to move to simpler Pydantic types and use functions to implement additional behavior as necessary.

Simplify extract types to support RT v2 pipeline

---

calitp/storage.py
pyproject.toml

This PR stops using `.removeprefix` because Cal-ITP Airflow is not on Python 3.9 yet (specifically, to unblock https://github.com/cal-itp/data-infra/pull/1696). 
This has been published as a pre-release: https://pypi.org/project/calitp/2022.8.25a0/. When PR is approved, I will bump to normal release & merge, to be used in https://github.com/cal-itp/data-infra/pull/1696 as a full release.
I have tested that I can run the new DAG task in https://github.com/cal-itp/data-infra/pull/1696 with this change and it works
<details>
<summary>Airflow output from successful run of new DAG task in #data-infra</summary>
```
listing all files in gs://test-calitp-gtfs-schedule-raw/schedule/dt=1901-01-01/
Identified 4 records for 1901-01-01
Processing …
```

Stop using removeprefix

---

calitp/auth.py
pyproject.toml

Make the secret loading easier to use; allow callers to either get a single secret by name or all secrets with a given label. Also, just return the secrets rather than setting on the environ, which is silly in retrospect. Just let the caller decide what to do.

just return the secrets and let the caller decide what to do

---

.gitignore
calitp/storage.py
pyproject.toml

Adds `computed` to `GTFSDownloadConfig` and `reconstructed` to `GTFSScheduleFeedExtract` to indicate backfilled objects.
Used in https://github.com/cal-itp/data-infra/pull/2033

add a couple fields for schedule backfill

---

calitp/tables.py
pyproject.toml

Some of our RT fact tables are materialized as views, which do not show up in calitp-py currently. This PR uses the new Inspector in sqlalchemy to get both tables and views from the engine for AutoTable.

use inspector for autotable and also add views

---

.pre-commit-config.yaml
calitp/auth.py
calitp/storage.py
pyproject.toml

Necessary for https://github.com/cal-itp/data-infra/issues/2046
Adds `**request_kwargs` to `download_feed` to let callers pass arguments such as timeouts to the underlying call to `send()`.
I've already published 2023.2.1 to pypi.

Add request kwargs to download_feed

---

calitp-data-analysis/README.md

This is a small change to the `calitp-data-analysis` package README, updating an import example that was missed when the packages were split into three.

Update README for analysis package to reflect new import string

---

calitp-data-infra/calitp_data_infra/storage.py
calitp-data-infra/pyproject.toml

Addresses #104, removing the redundant get_fs and redirecting references to it so that they source from calitp-data instead of calitp-data-infra. Also updates the version number on the calitp-data-infra package.

Remove get_fs from calitp-data-infra package
